// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HistoryAirQualityTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void historyAirQuality() {
    driver.get("https://tqs-mid-term-project.ew.r.appspot.com/");
    driver.manage().window().setSize(new Dimension(892, 666));
    driver.findElement(By.id("input_city")).click();
    driver.findElement(By.id("input_city")).sendKeys("Madrid");
    driver.findElement(By.id("input_country")).click();
    driver.findElement(By.id("input_country")).sendKeys("Espanha");
    driver.findElement(By.id("select_city")).click();
    driver.findElement(By.id("days_before")).click();
    driver.findElement(By.id("days_before")).sendKeys("2");
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("History air quality in Madrid"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(18) > th"));
      assert(elements.size() > 0);
    }
  }
}
